### ISSUE TITLE
How to do api call for api.eu.pagerduty.com ?

### ISSUE THREAD

**Issue by akhilesh0** [PagerDuty/pdpyras#108]

**Comment by Deconstrained** [comment]
Great question!

I recommend updating the `url` property of the session object:

```
session.url = 'api.eu.pagerduty.com'
```

Our load balancers have many ways of detecting if a key belongs to a different service region, but it's always better to explicitly use the service-region-specific host name because then traffic will go directly to it and latency will be lower.

Leaving this open for documentation or improvement.
