### ISSUE TITLE
429 0-retry logic not respected

### ISSUE THREAD

**Issue by andynelson34** [PagerDuty/pdpyras#139]
Re: rate limiting, [the docs say](https://pagerduty.github.io/pdpyras/user_guide.html#default-behavior)

> By default, after receiving a status 429 response, sessions will retry the request indefinitely until it receives a status other than 429, and this behavior cannot be overridden. This is a sane approach; if it is ever responding with 429, the REST API is receiving (for the given REST API key) too many requests, and the issue should by nature be transient unless there is a rogue process using the same API key and saturating its rate limit.
> 
> Also, it is default behavior when encountering status 401 Unauthorized for the client to immediately raise pdpyras.PDClientError; this is a non-transient error caused by an invalid credential.
> 
> However, both of these behaviors can be overridden by adding entries in the retry dictionary. For instance, it may be preferable to error out instead of hanging indefinitely to continually retry if another API process is saturating the rate limit.

But `PDSession.request` always retries indefinitely on a 429 if `retry_logic == 0`. Is this a bug or WAI?

**Comment by Deconstrained** [comment]
It's as expected.

To clarify, and the docs will be updated to avoid this confusion, setting `session.retry[429] = 0` or for any status beside 429 will be the same as not setting a value -- that is to say, the default behavior (retry on 429, raise exception on 401 and return for any other status) would be invoked.

Thank you also for pointing out this contradiction hiding in plain sight in the documentation 🤦 It is actually possible to override the default behavior for status 429 and have the client retry a finite number of times by setting `session.retry[429]` to a positive integer. That would provide a short-circuit option for rate-saturated keys i.e. because of another rogue process using the same key, or the current process (in which case stopping requests might help stem the tide, depending on how the error is handled).

**Comment by andynelson34** [comment]
Yeah, I wound up setting it to retry 1 time on a 429 as a workaround, and I think that's going to be good enough for my case, but just wanted to check. Thanks for clarifying!

**Comment by Deconstrained** [comment]
#140
