### ISSUE TITLE
PDClientError doesn't catch 400 for event_rules endpoint for bad format

### ISSUE THREAD

**Issue by TanjidIslam** [PagerDuty/pdpyras#18]
Reproduce with the following: 

```
from pdpyras import APISession, PDClientError

# Action is missing an extra layer of bracket 
# valid format is:
# 'actions': [['route', '<INSERT_SERVICE_ID>']]
payload = {'condition': ['and', ['contains', ['path', 'payload', 'source'], 'website'], ['contains', ['path', 'payload', 'source'], 'api']], 'actions': ['route', '<INSERT_SERVICE_ID>']}

try: 
    session = APISession(api_token)
    provision_event_rules = session.post("/event_rules", json=payload )
    print(provision_event_rules.status_code) # prints 400
    # prints: {'rules': [{'actions': ['expected array, received Elixir.Api.Schemas.MixedList']}]}
    print(provision_event_rules.json()) 
except PDClientError as e:
   print(e.response)
   print(e.response.url)
   print(e.response.text)
```

Never returns the 400 response

**Comment by Deconstrained** [comment]
Hi @TanjidIslam ,

Can you please share more details on exactly the observed behavior of the library versus its expected behavior? I'm not perceiving here what exactly is not happening correctly or as expected.

So far, as I can tell:

* `session.post` is expected to return an object of class `requests.Response`, and it does.
* Session objects won't raise for status 400 by default in `pdpyras.APISession.request` or any of the basic HTTP verb methods that return `requests.Response` objects.

**Comment by Deconstrained** [comment]
(Also note: the `r*` methods do not support the `/event_rules` endpoint because it doesn't adhere to the naming convention where the JSON structure follows from the name of the resource in the URL; see: [Supported Endpoints](https://pagerduty.github.io/pdpyras/#supported-endpoints).
