### ISSUE TITLE
Support for Events v2 API

### ISSUE THREAD

**Issue by jjm** [PagerDuty/pdpyras#3]
I'm really liking `pdpyras` for working with the PagerDuty API, however it would be really nice if could support the Events API too. As low level handling rate limits and errors for sending events from custom applications would be really helpful.

Usage would be something like:

```python
from pdpyras import EventSession

integration_key = 'your-token-here'
session = EventSession(integration_key)

event = {}

session.enqueue(event)
```

**Comment by Deconstrained** [comment]
Thanks for the input @jjm ! I'm going to start another "development cycle" on this project that will include support for multi-update endpoints, and I plan on including this one as well.

**Comment by jjm** [comment]
@Deconstrained Thanks for the update, I understand not wanting a quick solution. Look forward to seeing this when you have done some refactoring.

**Comment by Deconstrained** [comment]
@jjm Yesterday I reviewed my earlier work, ran some final tests and merged/published version 3 of the client, which includes a new class for triggering via the Events API. The new class for utilizing the Events API is called `EventsAPISession`.

Note, there are some typos in the documentation that I'm working on fixing in addition to some other general improvements.

**Comment by jjm** [comment]
@Deconstrained Thank you, looks awesome 💯

**Comment by Deconstrained** [comment]
@jjm Something I just realized would be necessary to avoid superfluous keyword arguments and also better document the `trigger` and `send_event` methods would be a lightweight refactor of the args specific to triggering into the `trigger` method.

I caught this just today going back and noticing a few holes in the documentation (sorry for missing that) and I wanted to run this by you first since you were the original requester, because it makes a potentially breaking change. One would be affected by this change only if calling `EventsAPISession.send_event` directly, and passing in `summary` and `dedup_key` as positional arguments rather than keyword arguments as they were intended to be passed.

The changes are in commit 3e7620c605f3aff1f58be1b443834eb65252fdec.

Please let me know what you think.

**Comment by Deconstrained** [comment]
FYI I have merged and am closing this issue again. The follow-up update is a somewhat trivial change and the longer it waits the greater the chances of it having impact.
