### ISSUE TITLE
Bug when posting to /schedules/{id}/overrides

### ISSUE THREAD

**Issue by sl-alexandrenerat** [PagerDuty/pdpyras#77]
Hi,

When posting to /schedules/{id}/overrides, logic defined here (https://github.com/PagerDuty/pdpyras/blob/main/pdpyras.py#L130):

```
if is_index and http_method=='get' or multi_put:
            # Plural resource name, for index action (GET /<resource>), or for
            # multi-update (PUT /<resource>). In both cases, the response
            # (former) or request (latter) body is {<resource>:[<objects>]}
            envelope_name = resource
        else:
            # Individual resource create/read/update
            # Body = {<singular-resource-type>: {<object>}}
            envelope_name = envelope_name_single
 ```

leads to the latter case in which we are updating an individual resource which is not the case. Specifically:
- is_index is true because url has 3 parts
- http_method is POST, so we fail in the else part

As a consequence, when performing session.rpost('/schedules/{id}/overrides', json=overrides), overrides provided are being encapsulated as a "override" property of an object.

Workaround is to pass overrides as:
overrides = {
  overrides= [ ... ],
  override = ''
}
Then, as override property is present, the whole object is being sent.

**Comment by jwrobb** [comment]
Hi @sl-alexandrenerat I believe I am having the same issue when attempting to post to /incidents/{uid}/snooze I wonder if I am encountering the same issue.

Curl requests to api.pagerduty.com for that path work correctly. However, when I try through pdpyras I get this

```console
POST /incidents/#####/snooze: API responded with non-success status (400): {"error":{"message":"Invalid Input Provided","code":2001}}
```

How did you troubleshoot this issue and identify where the problem was occurring? I am stuck determining how to move forward with gathering more information on what is going.

**Comment by sl-alexandrenerat** [comment]
@jwrobb I'm not sure it's the same bug actually as your api call doesn't post a list designated with a plural property.

Anyway to find out which was the problem I added debug to requests library (here https://gist.github.com/Daenyth/b57f8522b388e66fcf3b?permalink_comment_id=3194372#gistcomment-3194372) and also used a debugger to step into my call.

**Comment by Deconstrained** [comment]
Hello @sl-alexandrenerat,

Thank you for pointing this out. This is a counter-pattern in the API that I hadn't noticed before. It breaks `rpost` in this use case, but it doesn't need to.

An ideal fix would be defining a static list of endpoints at the top similar to `VALID_MULTI_UPDATE_PATHS`, i.e. `VALID_MULTI_CREATE_PATHS = [('schedules', '{id}', 'overrides')]` and then conjoin a similar thing to `multi_put` to the condition, i.e. 

```
        multi_post = http_method == 'post' and nodes in VALID_MULTI_CREATE_PATHS
        ...
        if is_index and http_method=='get' or multi_put or multi_post:
```

@jwrobb I recommend not using `rpost` for snoozing an incident because the endpoint isn't supported by the `r*` methods.

If you had been using regular old `post` instead, then it would be worth examining the value of the `json` argument and ensuring that it's a dictionary that looks something like `{"duration": 86400}`

**Comment by Deconstrained** [comment]
Upon further review, it looks like `POST /overrides` departs from API norms to an extent that makes it irreconcilable with the design of the `resource_envelope` decorator. This is because in the response, _there is no resource envelope_.

Per [the API docs](https://developer.pagerduty.com/api-reference/b3A6Mjc0ODE4OA-create-one-or-more-overrides), the root level of the response body is an _array of objects_, versus an object with a resource envelope. No resource envelope means there's nothing to extract from the response body. You can just call `session.jpost('/schedules/PSCHEDID/overrides', json={'overrides': [...]})` and the return value is the array of created overrides.

The only way to make `rpost` work with the create overrides endpoint is making a super special exception for just this particular API where it returns the response body in full, but that is treading into the territory of "making an API for the API" which goes against the design philosophy of this API client.
