### ISSUE TITLE
rput raises PDHTTPError from JSONDecodeError when adding a user to a team

### ISSUE THREAD

**Issue by mpjura** [PagerDuty/pdpyras#86]
Adding a user to a team with `client.rput(f'teams/{team}/users/{user}')` raises `PDHTTPError` from `JSONDecodeError` encountered trying to decode response text. The raw response from `put` is a 204 with no content.

Removing a user from a team with `client.rdelete(f'teams/{team}/users/{user}')` does not raise the same error even though the raw response is also a 204 with no content.

**Comment by Deconstrained** [comment]
Hi @mpjura, 

The `r*` methods assume that the endpoint they are used on has [entity wrapping](https://pagerduty.github.io/pdpyras/#wrapped-entities). That does not apply in the case of this endpoint.

One can get around this by simply using `put` instead of `rput`.

Nevertheless, it isn't explicitly listed as an endpoint that the `r*` methods don't support, so the documentation shall be updated.

**Comment by mpjura** [comment]
got it, thanks @Deconstrained
